// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.4
// source: computation/solver.proto

package computation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EquationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size      int32     `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Matrix    []float64 `protobuf:"fixed64,2,rep,packed,name=matrix,proto3" json:"matrix,omitempty"`
	Constants []float64 `protobuf:"fixed64,3,rep,packed,name=constants,proto3" json:"constants,omitempty"`
}

func (x *EquationRequest) Reset() {
	*x = EquationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_computation_solver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquationRequest) ProtoMessage() {}

func (x *EquationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_computation_solver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquationRequest.ProtoReflect.Descriptor instead.
func (*EquationRequest) Descriptor() ([]byte, []int) {
	return file_computation_solver_proto_rawDescGZIP(), []int{0}
}

func (x *EquationRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *EquationRequest) GetMatrix() []float64 {
	if x != nil {
		return x.Matrix
	}
	return nil
}

func (x *EquationRequest) GetConstants() []float64 {
	if x != nil {
		return x.Constants
	}
	return nil
}

type EquationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Solution []float64 `protobuf:"fixed64,1,rep,packed,name=solution,proto3" json:"solution,omitempty"`
	Error    string    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *EquationResponse) Reset() {
	*x = EquationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_computation_solver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquationResponse) ProtoMessage() {}

func (x *EquationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_computation_solver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquationResponse.ProtoReflect.Descriptor instead.
func (*EquationResponse) Descriptor() ([]byte, []int) {
	return file_computation_solver_proto_rawDescGZIP(), []int{1}
}

func (x *EquationResponse) GetSolution() []float64 {
	if x != nil {
		return x.Solution
	}
	return nil
}

func (x *EquationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_computation_solver_proto protoreflect.FileDescriptor

var file_computation_solver_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x72, 0x22, 0x5b, 0x0a, 0x0f, 0x45, 0x71, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x74,
	0x72, 0x69, 0x78, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x6d, 0x61, 0x74, 0x72, 0x69,
	0x78, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x73, 0x22,
	0x44, 0x0a, 0x10, 0x45, 0x71, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x08, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x4e, 0x0a, 0x06, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x12,
	0x44, 0x0a, 0x0d, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x45, 0x71, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x17, 0x2e, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x71, 0x75, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x72, 0x2e, 0x45, 0x71, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2e, 0x2f, 0x63, 0x6f, 0x6d, 0x70,
	0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_computation_solver_proto_rawDescOnce sync.Once
	file_computation_solver_proto_rawDescData = file_computation_solver_proto_rawDesc
)

func file_computation_solver_proto_rawDescGZIP() []byte {
	file_computation_solver_proto_rawDescOnce.Do(func() {
		file_computation_solver_proto_rawDescData = protoimpl.X.CompressGZIP(file_computation_solver_proto_rawDescData)
	})
	return file_computation_solver_proto_rawDescData
}

var file_computation_solver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_computation_solver_proto_goTypes = []interface{}{
	(*EquationRequest)(nil),  // 0: solver.EquationRequest
	(*EquationResponse)(nil), // 1: solver.EquationResponse
}
var file_computation_solver_proto_depIdxs = []int32{
	0, // 0: solver.Solver.SolveEquation:input_type -> solver.EquationRequest
	1, // 1: solver.Solver.SolveEquation:output_type -> solver.EquationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_computation_solver_proto_init() }
func file_computation_solver_proto_init() {
	if File_computation_solver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_computation_solver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_computation_solver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_computation_solver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_computation_solver_proto_goTypes,
		DependencyIndexes: file_computation_solver_proto_depIdxs,
		MessageInfos:      file_computation_solver_proto_msgTypes,
	}.Build()
	File_computation_solver_proto = out.File
	file_computation_solver_proto_rawDesc = nil
	file_computation_solver_proto_goTypes = nil
	file_computation_solver_proto_depIdxs = nil
}
